modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory (28 is current forge version)

license="GNU Lesser General Public License v3.0"

[[mods]] #mandatory
modId="connectiblechains" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Connectible Chains" #mandatory
logoFile="icon.png" #optional
credits="Legoatoom for creating the original fabric mod" #optional
authors="legoatoom, qendolin, lilypuree" #optional
description='''
Connect chains between fences
'''

[[dependencies.connectiblechains]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.connectiblechains]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
